# Generated by Django 4.1.3 on 2022-12-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_img_movie_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='pic',
            new_name='img',
        ),
    ]
